language: node_js
node_js:
- stable
notifications:
  email: true
  slack: webhouseteam:82qu1PX5R5wkYNCW5x6fVlhu

addons:
  ssh_known_hosts: kanata.webhouse.net

script:
- yarn
- yarn build
- cp ./build/index.html ./build/200.html
deploy:
  provider: surge
  project: "./build/"
  domain: odeumcodeapp.surge.sh
  skip_cleanup: true
  on:
    all_branches: true

before_install:
- openssl aes-256-cbc -K $encrypted_4b792e3e77a1_key -iv $encrypted_4b792e3e77a1_iv
  -in deploy_rsa.enc -out deploy_rsa -d
